print final success/failure status message
Note: working with -e is hard
Note2: The 'end' hook still runs after the final message

diff --git a/substitute b/substitute
--- a/substitute
+++ b/substitute
@@ -17,11 +17,11 @@ error() {
 
 hook() {
   script="${1}"
-  file="${script_dir}/$script.sh"
-  if [ -f "$file" ]; then
-    info "Running script hook '$script'"
-    if ! source "$file"; then
-      error "Script hook '$script' failed"
+  file="${script_dir}/${script}.sh"
+  if [ -f "${file}" ]; then
+    info "Running script hook '${script}'"
+    if ! source "${file}"; then
+      error "Script hook '${script}' failed"
       return 1
     fi
   fi
@@ -31,7 +31,7 @@ hook() {
 this="$(which "${0}")"
 whereami="$(cd "$( dirname "$(readlink "${this}" || echo "${this}")")"; pwd)"
 
-cd "$whereami"
+cd "${whereami}"
 
 deploy_dir="${whereami}/deploy"
 script_dir="${deploy_dir}/scripts"
@@ -68,7 +68,7 @@ start() {
 }
 
 stop() {
-  stop_name="$1"
+  stop_name="${1}"
   hook "pre_stop"
 
   info "Shutting down ${stop_name} ..."
@@ -160,16 +160,13 @@ substitute() {
   stop "${stop_app}"
   info "Setting next_deploy to ${stop_app}"
   echo "${stop_char}" > "${nd_file}"
-
-  tput setf 2; echo -e "\n> ${action} completed!\n"; tput sgr0
 }
 
-case "${1}" in
+action="${1}"
+case "${action}" in
 deploy)
-  action="deploy"
   substitute "${2}";;
 rollback)
-  action="rollback"
   substitute;;
 start)
   start "${2}" "${3}" "${4}" "${5}";;
@@ -177,10 +174,18 @@ stop)
   stop "${2}";;
 *)
   echo "Usage:"
-  echo "  $0 deploy [COMMIT]"
-  echo "  $0 rollback"
-  echo "  $0 start <APP_NAME> <APP_DIR> <HOST> <PORT>"
-  echo "  $0 stop <APP_NAME>"
-esac
+  echo "  ${0} deploy [COMMIT]"
+  echo "  ${0} rollback"
+  echo "  ${0} start <APP_NAME> <APP_DIR> <HOST> <PORT>"
+  echo "  ${0} stop <APP_NAME>"
+esac && success="true" || success="false"
+
+echo ""
+if [ "${success}" == "true" ]; then
+  tput setf 2; echo -e "> Action ${action} completed."; tput sgr0
+else
+  error "Action ${action} failed."
+fi
+echo ""
 
 hook "end"
